-- GENERATED FILE - DO NOT EDIT BY HAND.
-- Source of truth: src/lib/permissions/policy.ts
-- Regenerate with: npm run gen:permissions
-- A test fails if this file is out of date.
--
-- Admin is not listed: Admin can do everything in a workspace they administer.

begin;

-- The most each role can ever hold. Admin grants can never exceed this.
delete from public.permission_ceiling;
insert into public.permission_ceiling (role, module, action) values
  ('team_member', 'seo_geo', 'view'),
  ('team_member', 'seo_geo', 'create'),
  ('team_member', 'seo_geo', 'edit'),
  ('team_member', 'seo_geo', 'approve'),
  ('team_member', 'seo_geo', 'publish_execute'),
  ('team_member', 'seo_geo', 'delete'),
  ('team_member', 'paid_ads', 'view'),
  ('team_member', 'paid_ads', 'create'),
  ('team_member', 'paid_ads', 'edit'),
  ('team_member', 'paid_ads', 'approve'),
  ('team_member', 'paid_ads', 'publish_execute'),
  ('team_member', 'paid_ads', 'delete'),
  ('team_member', 'domains', 'view'),
  ('team_member', 'domains', 'create'),
  ('team_member', 'domains', 'edit'),
  ('team_member', 'domains', 'approve'),
  ('team_member', 'domains', 'publish_execute'),
  ('team_member', 'domains', 'delete'),
  ('team_member', 'website', 'view'),
  ('team_member', 'website', 'create'),
  ('team_member', 'website', 'edit'),
  ('team_member', 'website', 'approve'),
  ('team_member', 'website', 'publish_execute'),
  ('team_member', 'website', 'delete'),
  ('team_member', 'ai_assistant', 'view'),
  ('team_member', 'social', 'view'),
  ('team_member', 'social', 'create'),
  ('team_member', 'social', 'edit'),
  ('team_member', 'social', 'approve'),
  ('team_member', 'social', 'publish_execute'),
  ('team_member', 'social', 'delete'),
  ('team_member', 'leads_crm', 'view'),
  ('team_member', 'leads_crm', 'create'),
  ('team_member', 'leads_crm', 'edit'),
  ('team_member', 'leads_crm', 'approve'),
  ('team_member', 'leads_crm', 'publish_execute'),
  ('team_member', 'leads_crm', 'delete'),
  ('team_member', 'reports', 'view'),
  ('team_member', 'reports', 'create'),
  ('team_member', 'reports', 'edit'),
  ('team_member', 'reports', 'approve'),
  ('team_member', 'reports', 'publish_execute'),
  ('team_member', 'reports', 'delete'),
  ('team_member', 'billing', 'view'),
  ('team_member', 'billing', 'billing'),
  ('team_member', 'change_requests', 'view'),
  ('team_member', 'change_requests', 'create'),
  ('team_member', 'change_requests', 'edit'),
  ('team_member', 'change_requests', 'approve'),
  ('team_member', 'change_requests', 'publish_execute'),
  ('team_member', 'change_requests', 'delete'),
  ('team_member', 'integrations', 'view'),
  ('team_member', 'integrations', 'manage_integration'),
  ('client', 'seo_geo', 'view'),
  ('client', 'seo_geo', 'create'),
  ('client', 'seo_geo', 'publish_execute'),
  ('client', 'paid_ads', 'view'),
  ('client', 'paid_ads', 'create'),
  ('client', 'paid_ads', 'edit'),
  ('client', 'paid_ads', 'publish_execute'),
  ('client', 'paid_ads', 'delete'),
  ('client', 'domains', 'view'),
  ('client', 'domains', 'create'),
  ('client', 'domains', 'edit'),
  ('client', 'domains', 'publish_execute'),
  ('client', 'domains', 'delete'),
  ('client', 'website', 'view'),
  ('client', 'ai_assistant', 'view'),
  ('client', 'social', 'view'),
  ('client', 'social', 'create'),
  ('client', 'social', 'edit'),
  ('client', 'social', 'approve'),
  ('client', 'leads_crm', 'view'),
  ('client', 'leads_crm', 'create'),
  ('client', 'leads_crm', 'edit'),
  ('client', 'leads_crm', 'delete'),
  ('client', 'reports', 'view'),
  ('client', 'billing', 'view'),
  ('client', 'billing', 'billing'),
  ('client', 'change_requests', 'view'),
  ('client', 'change_requests', 'create');

-- What each role holds before any Admin grant.
delete from public.permission_defaults;
insert into public.permission_defaults (role, module, action) values
  ('client', 'seo_geo', 'view'),
  ('client', 'seo_geo', 'create'),
  ('client', 'website', 'view'),
  ('client', 'ai_assistant', 'view'),
  ('client', 'social', 'view'),
  ('client', 'leads_crm', 'view'),
  ('client', 'reports', 'view'),
  ('client', 'change_requests', 'view'),
  ('client', 'change_requests', 'create');

-- Sensitive actions: always audited; a non-admin who is allowed to do one must get approval.
delete from public.permission_sensitive;
insert into public.permission_sensitive (module, action) values
  ('seo_geo', 'publish_execute'),
  ('seo_geo', 'delete'),
  ('seo_geo', 'grant_permission'),
  ('paid_ads', 'edit'),
  ('paid_ads', 'publish_execute'),
  ('paid_ads', 'delete'),
  ('paid_ads', 'grant_permission'),
  ('domains', 'create'),
  ('domains', 'edit'),
  ('domains', 'publish_execute'),
  ('domains', 'delete'),
  ('domains', 'grant_permission'),
  ('website', 'publish_execute'),
  ('website', 'delete'),
  ('website', 'grant_permission'),
  ('ai_assistant', 'publish_execute'),
  ('ai_assistant', 'delete'),
  ('ai_assistant', 'grant_permission'),
  ('social', 'publish_execute'),
  ('social', 'delete'),
  ('social', 'grant_permission'),
  ('leads_crm', 'delete'),
  ('leads_crm', 'grant_permission'),
  ('reports', 'delete'),
  ('reports', 'grant_permission'),
  ('billing', 'delete'),
  ('billing', 'billing'),
  ('billing', 'grant_permission'),
  ('change_requests', 'delete'),
  ('change_requests', 'grant_permission'),
  ('integrations', 'delete'),
  ('integrations', 'manage_integration'),
  ('integrations', 'grant_permission'),
  ('approvals', 'approve'),
  ('approvals', 'delete'),
  ('approvals', 'grant_permission'),
  ('audit_log', 'delete'),
  ('audit_log', 'grant_permission'),
  ('health_monitor', 'delete'),
  ('health_monitor', 'grant_permission'),
  ('settings', 'delete'),
  ('settings', 'grant_permission'),
  ('clients', 'create'),
  ('clients', 'delete'),
  ('clients', 'grant_permission');

commit;
